---
galaxy_info:
  author: Yosef
  description: Recurso compartido que da sentido al flujo USERS -> srv-app:445
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions: ["9"]
  galaxy_tags: []
dependencies: []
