---
galaxy_info:
  author: Yosef
  description: BIND autoritativo de lab.interno con zona inversa (AlmaLinux, paquete bind)
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions: ["9"]
  galaxy_tags: []
dependencies: []
